//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPORT_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int ID_comments { get; set; }
        public string posted_by { get; set; }
        public Nullable<System.DateTime> posted_on { get; set; }
        public string comment1 { get; set; }
        public Nullable<int> ID_parent { get; set; }
        public Nullable<int> ID_ticket { get; set; }
        public Nullable<int> ID_user { get; set; }
        public string username { get; set; }
    
        public virtual ticket ticket { get; set; }
        public virtual user user { get; set; }
    }
}
