//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPORT_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class section
    {
        public int ID_sections { get; set; }
        public string section_name { get; set; }
        public string description { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual user user { get; set; }
    }
}
