//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUPORT_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ticket()
        {
            this.comments = new HashSet<comment>();
        }
    
        public int ID_ticket { get; set; }
        public Nullable<int> ID_suggestion { get; set; }
        public string title { get; set; }
        public Nullable<int> ID_status { get; set; }
        public string category { get; set; }
        public Nullable<int> ID_severity { get; set; }
        public string priority { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<System.DateTime> raised_on { get; set; }
        public Nullable<System.DateTime> due_on { get; set; }
        public Nullable<System.DateTime> resolved_on { get; set; }
        public string system_section { get; set; }
        public string steps_to_reproduce { get; set; }
        public string resolve_note { get; set; }
    
        public virtual severity severity { get; set; }
        public virtual status status { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
    }
}
